INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (1, 'Fecha', '../../assets/img/categoria_1.png', null, 'seleccion-fecha');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (2, 'Sedes', '../../assets/img/categoria_2.png', null, 'seleccion-categoria');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (3, 'Artistas', '../../assets/img/categoria_3.png', null, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (4, 'Disciplinas', '../../assets/img/categoria_4.png', null, 'seleccion-categoria');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (5, 'Eje Temático', '../../assets/img/categoria_5.png', null, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (6, 'Exposiciones', '../../assets/img/categoria_6.png', null, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (7, 'Eventos adicionales', '../../assets/img/categoria_7.png', null, 'seleccion-categoria');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (8, 'Música', '../../assets/img/categoria_8.png', 4, 'seleccion-categoria');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (9, 'Teatro', '../../assets/img/categoria_9.png', 4, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (10, 'Danza', '../../assets/img/categoria_10.png', 4, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (11, 'Infantil', '../../assets/img/categoria_11.png', 4, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (20, 'Cineteca', '../../assets/img/categoria_20.png', 7, 'seleccion-categoria');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (21, 'Programa Académico', '../../assets/img/categoria_21.png', 7, 'programa-academico');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (22, 'Culturas Populares', '../../assets/img/categoria_22.png', 7, 'seleccion-categoria');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (23, 'Desfile', '../../assets/img/categoria_23.png', 22, 'desfile-descripcion');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (24, 'Fiesta del Pulque', '../../assets/img/categoria_24.png', 22, 'pulque-descripcion');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (25, 'Alianza Francesa', '../../assets/img/categoria_25.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (26, 'Anexo de la Capilla de Mexicapan', '../../assets/img/categoria_26.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (27, 'Antiguo Templo de San Agustín', '../../assets/img/categoria_27.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (28, 'COZCYT', '../../assets/img/categoria_28.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (29, 'Catedral Basílica', '../../assets/img/categoria_29.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (30, 'Cineteca Zacatecas', '../../assets/img/categoria_30.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (31, 'Centro Cultural Ciudadela del Arte', '../../assets/img/categoria_31.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (32, 'Centro de Multimedios El Sótano', '../../assets/img/categoria_32.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (33, 'Congreso del Estado', '../../assets/img/categoria_33.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (34, 'Explanada del Cerro de la Bufa', '../../assets/img/categoria_34.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (35, 'Galería Arroyo de la Plata', '../../assets/img/categoria_35.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (36, 'Galería Irma Valerio', '../../assets/img/categoria_36.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (37, 'Jardín Independencia', '../../assets/img/categoria_37.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (38, 'Multiforo', '../../assets/img/categoria_38.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (39, 'Museo Francisco Goitia', '../../assets/img/categoria_39.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (40, 'Museo de Arte Abstracto Manuel Felguérez', '../../assets/img/categoria_40.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (41, 'Museo El Universo de Pedro Coronel', '../../assets/img/categoria_41.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (42, 'Museo Rafel Coronel', '../../assets/img/categoria_42.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (43, 'Museo Zacatecano', '../../assets/img/categoria_43.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (44, 'Museo Interactivo de Ciencia y Tecnología Zig', '../../assets/img/categoria_44.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (45, 'Librería André-a', '../../assets/img/categoria_45.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (46, 'Plaza de Armas', '../../assets/img/categoria_46.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (47, 'Plazuela Goitia', '../../assets/img/categoria_47.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (48, 'Plazuela Miguel Auza', '../../assets/img/categoria_48.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (49, 'Presidencia Municipal de Valparaíso', '../../assets/img/categoria_49.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (50, 'Teatro Fernando Calderón', '../../assets/img/categoria_50.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (51, 'Teatro del IMSS', '../../assets/img/categoria_51.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (52, 'Teatro Ramón López Velarde', '../../assets/img/categoria_52.png', 2, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (53, 'Alternativo', '../../assets/img/categoria_53.png', 8, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (54, 'Antología', '../../assets/img/categoria_54.png', 8, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (55, 'Blues', '../../assets/img/categoria_55.png', 8, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (56, 'Bolero', '../../assets/img/categoria_56.png', 8, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (57, 'Cantautor', '../../assets/img/categoria_57.png', 8, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (58, 'Música del Mundo', '../../assets/img/categoria_58.png', 8, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (59, 'Contemporánea', '../../assets/img/categoria_59.png', 8, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (60, 'Electrónica', '../../assets/img/categoria_60.png', 8, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (61, 'Guitarra Clásica', '../../assets/img/categoria_61.png', 8, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (62, 'Hip-Hop', '../../assets/img/categoria_62.png', 8, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (63, 'Indie', '../../assets/img/categoria_63.png', 8, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (64, 'Jazz', '../../assets/img/categoria_64.png', 8, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (65, 'Latinoamericana', '../../assets/img/categoria_65.png', 8, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (66, 'Mexicana', '../../assets/img/categoria_66.png', 8, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (67, 'Música de cámara', '../../assets/img/categoria_67.png', 8, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (68, 'Ópera', '../../assets/img/categoria_68.png', 8, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (69, 'Percusiones', '../../assets/img/categoria_69.png', 8, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (70, 'Pop', '../../assets/img/categoria_70.png', 8, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (71, 'Rock', '../../assets/img/categoria_71.png', 8, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (72, 'Rock Zacatecano', '../../assets/img/categoria_72.png', 8, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (73, 'Sacra', '../../assets/img/categoria_73.png', 8, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (74, 'Sinfónica', '../../assets/img/categoria_74.png', 8, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (75, 'Ska', '../../assets/img/categoria_75.png', 8, 'eventos-lista');
INSERT INTO festival_cultural.categoria (id, nombre, icono, categoria_padre_id, link) VALUES (76, 'Tropical', '../../assets/img/categoria_76.png', 8, 'eventos-lista');

INSERT INTO sede (id, lat, lon, categoria_id) VALUES (1, 22.7749094, -102.576721, 25);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (2, 22.786154, -102.570669, 26);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (3, 22.7743365, -102.5764295, 27);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (4, 22.7611789, -102.5812676, 28);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (5, 22.7757185, -102.5723998, 29);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (6, 22.7751595, -102.5765076, 30);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (7, 22.7749003, -102.5762327, 31);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (8, 22.7714599, -102.576478, 32);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (9, 22.7744023, -102.5770845, 33);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (10, 22.778009, -102.56559, 34);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (11, 22.7734481, -102.5783847, 35);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (12, 22.7748848, -102.5761692, 36);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (13, 22.7713186, -102.5758292, 37);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (14, 22.7680115, -102.554546, 38);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (15, 22.7702726, -102.5797745, 39);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (16, 22.780614, -102.5745617, 40);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (17, 22.776116, -102.5758293, 41);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (18, 22.7821645, -102.5720409, 42);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (19, 22.77504, -102.5759387, 43);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (20, 22.761502, -102.5804437, 44);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (21, 22.7757109, -102.5754837, 45);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (22, 22.7760653, -102.5740353, 46);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (23, 22.7752393, -102.5733325, 47);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (24, 22.773942, -102.5742876, 48);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (25, 22.7784175, -103.5902526, 49);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (26, 22.7750654, -102.5752913, 50);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (27, 22.775195, -102.5809887, 51);
INSERT INTO sede (id, lat, lon, categoria_id) VALUES (28, 22.7571028, -102.5810176, 52);
